apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
  - namespace.yaml
  - ../../base

configMapGenerator:
  - name: demo
    behavior: replace
    literals:
      - APP_ENV=prod

patches:
- target:
    version: v1
    kind: Service
    name: demo
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30080
- target:
    version: v1
    kind: Deployment
    name: demo
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
