apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - namespace.yaml
  - ../../base

configMapGenerator:
  - name: demo
    behavior: merge
    literals:
      - APP_ENV=dev

patches:
- target:
    version: v1
    kind: Service
    name: demo
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30088
